pipeline
{
 agent any
  stages
  {
   stage("Conexion con Jenkins")
    {
     steps
     {
      echo "java: "
      bat "java -version"
      echo "git "
      bat "git --version"
     }
    }
  }  
}
